#!/bin/bash

# ============================================================
# 🚀 New Project Setup Script
# ============================================================
#
# This script automates the initial setup of a new project
# from the boilerplate.
#
# Usage: ./scripts/setup-new-project.sh
#
# ============================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
print_header() {
    echo -e "\n${BLUE}============================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}============================================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Welcome message
clear
print_header "🚀 Boilerplate New Project Setup"

echo "This script will help you configure a new project from the boilerplate."
echo "It will guide you through:"
echo "  1. Configuring Git remotes"
echo "  2. Customizing site configuration"
echo "  3. Setting up environment variables"
echo "  4. Installing dependencies"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    print_error "Setup cancelled"
    exit 1
fi

# ============================================================
# Step 1: Git Configuration
# ============================================================

print_header "Step 1: Git Configuration"

# Check if we're in a git repository
if [ ! -d .git ]; then
    print_error "Not a git repository. Please run this script from the project root."
    exit 1
fi

# Check current remotes
echo "Current git remotes:"
git remote -v
echo ""

# Ask if user wants to configure remotes
read -p "Do you want to configure git remotes? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Check if origin exists
    if git remote | grep -q "^origin$"; then
        print_warning "Remote 'origin' exists. Renaming to 'upstream'..."
        git remote rename origin upstream || print_warning "Could not rename origin to upstream"
    fi

    # Ask for new origin URL
    echo ""
    echo "Enter your NEW project repository URL (e.g., https://github.com/USERNAME/my-project.git):"
    read -r NEW_ORIGIN_URL

    if [ -n "$NEW_ORIGIN_URL" ]; then
        # Remove existing origin if it exists
        git remote remove origin 2>/dev/null || true

        # Add new origin
        git remote add origin "$NEW_ORIGIN_URL"
        print_success "Added new origin: $NEW_ORIGIN_URL"
    fi

    # Ensure upstream exists
    if ! git remote | grep -q "^upstream$"; then
        print_warning "Adding boilerplate as upstream..."
        git remote add upstream https://github.com/Gnol86/BLP.git
    fi

    # Show updated remotes
    echo ""
    echo "Updated git remotes:"
    git remote -v
fi

# Configure merge strategies
print_success "Configuring git merge strategies..."
git config merge.ours.driver true
git config merge.theirs.driver true

# ============================================================
# Step 2: Site Configuration
# ============================================================

print_header "Step 2: Site Configuration"

echo "Let's customize your site configuration (src/site-config.js)"
echo ""

read -p "Project name (e.g., 'My Awesome App'): " PROJECT_NAME
read -p "Project description: " PROJECT_DESC
read -p "Production URL (e.g., 'https://myapp.com'): " PROD_URL
read -p "Domain (e.g., 'myapp.com'): " DOMAIN
read -p "App ID (lowercase, no spaces, e.g., 'myapp'): " APP_ID
read -p "Company name: " COMPANY_NAME
read -p "Team name: " TEAM_NAME
read -p "Contact email (e.g., 'info@myapp.com'): " CONTACT_EMAIL
read -p "No-reply email (e.g., 'noreply@myapp.com'): " NOREPLY_EMAIL
read -p "Primary brand color (e.g., '#6366F1'): " BRAND_COLOR

# Update site-config.js
print_success "Updating src/site-config.js..."

cat > src/site-config.js << EOF
/**
 * ============================================================
 * PROJECT CONFIGURATION
 * ============================================================
 *
 * This file was automatically generated by setup-new-project.sh
 * You can manually edit these values at any time.
 *
 * ============================================================
 */

export const SiteConfig = {
    // ========== SITE INFORMATION ==========
    title: "${PROJECT_NAME}",
    description: "${PROJECT_DESC}",
    prodUrl: "${PROD_URL}",
    appId: "${APP_ID}",
    domain: "${DOMAIN}",
    appIcon: "/images/logo.png",

    // ========== COMPANY INFORMATION ==========
    company: {
        name: "${COMPANY_NAME}",
    },

    // ========== TEAM INFORMATION ==========
    team: {
        website: "${PROD_URL}",
        name: "${TEAM_NAME}",
        email: "${CONTACT_EMAIL}",
    },

    // ========== EMAIL CONFIGURATION ==========
    mail: {
        from: "${PROJECT_NAME} <${NOREPLY_EMAIL}>",
        name: "${PROJECT_NAME}",
        email: "${NOREPLY_EMAIL}",
        replyTo: "${CONTACT_EMAIL}",
        signature: "The ${PROJECT_NAME} Team",
    },

    // ========== BRAND STYLING ==========
    brand: {
        primary: "${BRAND_COLOR}",
    },

    // ========== ORGANIZATION SETTINGS ==========
    options: {
        organization: {
            allowUserToCreateOrganization: true,
            organizationLimit: 5,
            membershipLimit: 9999,
            invitationLimit: 9999,
            invitationExpiresIn: 60 * 60 * 24 * 30, // 30 days
        },
    },

    // ========== BILLING CONFIGURATION ==========
    billing: {
        type: "plan", // "seat" or "plan" or "subscription"
    },
};
EOF

print_success "Site configuration updated!"

# ============================================================
# Step 3: Environment Variables
# ============================================================

print_header "Step 3: Environment Variables"

if [ -f .env ]; then
    print_warning ".env file already exists. Skipping..."
else
    if [ -f .env.example ]; then
        cp .env.example .env
        print_success "Created .env from .env.example"
        print_warning "⚠️  IMPORTANT: Edit .env and add your actual values!"
    else
        print_warning "No .env.example found. Please create .env manually."
    fi
fi

# ============================================================
# Step 4: Dependencies
# ============================================================

print_header "Step 4: Dependencies"

read -p "Install dependencies now? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    print_success "Installing dependencies with pnpm..."
    pnpm install

    print_success "Generating Prisma client..."
    pnpm prisma generate
fi

# ============================================================
# Step 5: Summary & Next Steps
# ============================================================

print_header "✅ Setup Complete!"

echo -e "${GREEN}Your project has been configured!${NC}"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Review and edit your .env file:"
echo "   ${BLUE}vim .env${NC}"
echo ""
echo "2. Replace brand images:"
echo "   ${BLUE}public/images/logo.png${NC}"
echo "   ${BLUE}public/images/icon.png${NC}"
echo ""
echo "3. Customize your landing page:"
echo "   ${BLUE}src/app/page.js${NC}"
echo ""
echo "4. Customize your theme colors:"
echo "   ${BLUE}src/app/globals.css${NC}"
echo ""
echo "5. Start development server:"
echo "   ${BLUE}pnpm dev${NC}"
echo ""
echo "6. Create your first project code:"
echo "   ${BLUE}src/project/components/my-component.jsx${NC}"
echo ""
echo "7. Add project translations:"
echo "   ${BLUE}src/messages/*.project.json${NC}"
echo ""
echo "8. Create database models:"
echo "   ${BLUE}prisma/schema/project.prisma${NC}"
echo ""
echo "📚 Documentation:"
echo "   - Setup guide: ${BLUE}.github/SETUP_NEW_PROJECT.md${NC}"
echo "   - Project structure: ${BLUE}src/project/README.md${NC}"
echo "   - Code examples: ${BLUE}src/project/examples/${NC}"
echo ""
print_success "Happy coding! 🎉"
